<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"机构人员管理",
                        "menuJump":"列表",
                        "tableName":"jigou"
                    }
                ],
                "menu":"机构人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除",
                            "报表"
                        ],
                        "menu":"就业信息管理",
                        "menuJump":"列表",
                        "tableName":"jiuye"
                    }
                ],
                "menu":"就业信息管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学校管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_xuexiao"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学院管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_xueyuan"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"专业管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_zhuanye"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"部门管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_bumen"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"职位管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_zhiwei"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"地区管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_diqu"
                    }
                ],
                "menu":"基础数据管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	
	
	
	,{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "报表"
                        ],
                        "menu":"就业信息管理",
                        "menuJump":"列表",
                        "tableName":"jiuye"
                    }
                ],
                "menu":"就业信息管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"机构",
        "tableName":"jigou"
    }
	
	,{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"就业信息管理",
                        "menuJump":"列表",
                        "tableName":"jiuye"
                    }
                ],
                "menu":"就业信息管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
